apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zqyhnizlp-go 
  janus-idp.io/tekton: zqyhnizlp-go
  backstage.io/kubernetes-id: zqyhnizlp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zqyhnizlp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  